<?php
?>
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.2.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css">
	</head>
	<body>
		<h1 class="text-center">LEGAL NOTICE</h1>
		<h1 class="text-center">TO ALL DOG OWNERS</h1>
		
		<p>According to Connection General Statute 22-238, you are required to license your dog(s) in the month of June.  The fee for licensing shall be $8.00 for spayed/neutered dogs and $19.00 for unspayed/unneutered dogs.</p>
		<p>Dog licenses may be renewed by mail.  Information required: name, address, phone number, email address, name of dog, breed, age/birthdate, color, and enclose a self-addressed stamped envelope.  You are also required to provide a copy of proof of current rabies vaccination and proof of neutering/spaying when licensing your dog(s).</p>  
		<p class="text-decoration-underline">YOU MUST PROVIDE AN UPDATED COPY OF THE DOG'S RABIES VACCINATION CERTIFICATE.  WE WILL NOT CONTACT YOUR VETERNARIAN FOR YOU.</p>
		<p>Dog licenses will be issued strictly through the mail, please make checks payable to the Town Clerk and mail to:</p>
		<address>
			Town Clerk's Office<br>
			245 deKoven Drive, Room 110<br>
			Middletown, CT  06457-1300<br>
		</address>
		
		<p>The period for licensing your dog(s) is June 1 through June 30.  After this date, you will be penalized $1.00 per month for each month that you fail to license your dog(s).</p>
		
		<blockquote>
		Ashley Flynn-Natale<br>
		City and Town Clerk<br>
		City of Middletown<br>
		</blockquote>
		
    </body>
</html>