<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js')
            ->prependFile('https://code.jquery.com/jquery-3.3.1.slim.min.js')
        ?>
    </head>
    <body>
    	<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
        	<a class="navbar-brand" href="<?= $this->url('home') ?>">
        		<img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>" />&nbsp;Skeleton Application
        	</a>
        	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        		<span class="navbar-toggler-icon"></span>
        	</button>
        	<div class="collapse navbar-collapse" id="navbarNav">
        	<?= $this->navigation('Zend\Navigation\Default')->menu()->setPartial('navigation'); ?>
            <?= $this->navigation('Zend\Navigation\User')->menu()->setPartial('user/partial/navigation.phtml'); ?>
    		</div>
		</nav>
        <div class="container mt-3">
        <!-- Flash Messenger -->
            <?php echo $this->partial('flashmessenger'); ?>
        	
            <?= $this->content ?>
            <hr>
            <footer id="footer">
                &copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.
            </footer>
        </div>
        <?= $this->inlineScript() 

        ?>
    </body>
</html>
