<?php
use Dog\Form\DogSearchForm;
use Dog\Form\LicenseSearchForm;
use Dog\Form\OwnerSearchForm;
use Dog\Form\StreetSearchForm;

$this->headScript()
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/excanvas.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.resize.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.time.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.canvas.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.categories.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.crosshair.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.errorbars.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.fillbetween.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.navigate.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.image.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.stack.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.symbol.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.threshold.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.js');
?>
<script type="text/javascript">
    $(function() {
    	var d1 = [];
		for (var i = 0; i < 12; i += .025) {
			d1.push([i, Math.sin(i)]);
		}
        
        $("#footer").append(" &ndash; Flot " + $.plot.version);

        $.plot("#incomechart", [ d1 ]);
    });

    
</script>

<div class="card-deck">
	<div class="card mb-4">
		<div class="card-header">
			<b>Find by Street</b>
		</div>
		<div class="card-body">
			<?php 
			$form = new StreetSearchForm();
			$form->initialize();
			$form->setAttribute('action', $this->url('dog/dog', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('NAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
	
	<div class="card mb-4">
		<div class="card-header">
			<b>Find by Owner</b>
		</div>
		<div class="card-body">
			<?php 
			$form = new OwnerSearchForm();
			$form->initialize();
			$form->setAttribute('action', $this->url('dog/owner', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('LNAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
	
	<div class="w-100 d-none d-sm-block d-lg-none"><!-- Wrap every 2 on md --></div>
	
	<div class="card mb-4">
		<div class="card-header">
			<b>Find by Dog</b>
		</div>
		<div class="card-body">
			<?php 
			$form = new DogSearchForm();
			$form->initialize();
			$form->setAttribute('action', $this->url('dog/dog', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('NAME')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
	
	<div class="card mb-4">
		<div class="card-header">
			<b>Find by Tag</b>
		</div>
		<div class="card-body">
			<?php 
			$form = new LicenseSearchForm();
			$form->initialize();
			$form->setAttribute('action', $this->url('dog/license', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SECURITY')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('TAG')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('YEAR')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('SUBMIT')); ?>
			</div>
			<?php
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
</div>

<div class="card-deck">
	<div class="card mb-4">
		<div class="card-header">
			<h4>Dog Licensing Income</h4>
		</div>
		<div class="card-body">
			<div id="incomechart" style="padding: 0px; height: 320px;">
				<canvas style="width: 100%; height: 100%;"></canvas>
			</div>
		</div>
	</div>
	
	<div class="w-100 d-none d-sm-block d-lg-none"><!-- Wrap every 2 on md --></div>
	
	<div class="card mb-4">
		<div class="card-header">
			<h4>License Ratio</h4>
		</div>
		<div class="card-body">
			<div id="licenseratio" style="padding: 0px; height: 320px;">
				<canvas style="width: 100%; height: 100%;"></canvas>
			</div>
		</div>
	</div>
</div>


